package training.web.controller.concrete;

public enum CommandName {
    DO_AUTH, DO_REGISTRATION, DO_LOGOUT, DO_ADD_NEWS,
    DO_CHANGE_LOCALE, DO_UPDATE_NEWS, DO_DELETE_NEWS,
    DO_NEWS_BY_TAG,

    GO_TO_REGISTRATION_PAGE, GO_TO_AUTH, GO_TO_INDEX_PAGE,GO_TO_MAIN_PAGE,
    GO_TO_ADD_NEWS_PAGE, GO_TO_ERROR_PAGE, GO_TO_FULL_NEWS_PAGE,
    GO_TO_UPDATE_NEWS_PAGE, GO_TO_NEWS_BY_TAGS_PAGE,

    NO_SUCH_COMMAND
}
